# Generated by Django 5.0.4 on 2024-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("some_app", "0002_alter_guest_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="guest",
            unique_together={("name", "phone")},
        ),
    ]
